---
- name: creating server EC2 Build on AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secret_file.yml

  roles:
    - build_aws

- name: creating server EC2 Prod on AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secret_file.yml

  roles:
    - prod_aws

- name: bootstrapping server Build on EC2
  hosts: build_ec2
  become: yes

  roles:
    - role_build