---
- name: Bootstrapping server EC2 Build on AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secret_file.yml

  roles:
    - build_aws

- name: Bootstrapping server EC2 Prod on AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secret_file.yml

  roles:
    - prod_aws