---
# tasks file for build_aws
- name: Creating EC2 security group
  amazon.aws.ec2_security_group:
    name: "{{ aws_name_security_group }}"
    description: EC2 group
    vpc_id: "{{ aws_vpc_id_security_group }}"
    rules:
      - proto: "{{ aws_protocol_security_group }}"
        from_port: "{{ aws_from_port_security_group }}"
        to_port: "{{ aws_to_port_security_group }}"
        cidr_ip: "{{ aws_cidr_ip_security_group }}"

- name: Creating EC2 Build on AWS
  amazon.aws.ec2_instance:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ ec2_name }}"
    instance_type: "{{ aws_instance }}"
    image_id: "{{ aws_ami_id }}"
    key_name: "{{ key }}"
    wait: true