---
# tasks file for build_aws
- name: Creating EC2 Build on AWS
  amazon.aws.ec2_instance:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ ec2_name }}"
    instance_type: "{{ aws_instance }}"
    image_id: ami-01fd6fa49060e89a6
    key_name: "{{ key }}"
    wait: true