---
# tasks file for build_aws
- name: creating EC2 security group
  amazon.aws.ec2_security_group:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ aws_name_security_group }}"
    description: EC2 group
    rules:
      - proto: "{{ aws_protocol_security_group }}"
        from_port: "{{ aws_from_port_security_group }}"
        to_port: "{{ aws_to_port_security_group }}"
        cidr_ip: "{{ aws_cidr_ip_security_group }}"

#- name: create a new EC2 key pair and save private key into a file
#  amazon.aws.ec2_key:
#    aws_access_key_id: "{{ aws_access_key }}"
#    aws_secret_access_key: "{{ aws_secret_key }}"
#    region: "{{ aws_region }}"
#    name: "{{ aws_key_name }}"
#    file_name: "{{ aws_file_name_key }}"
#  no_log: true

- name: creating EC2 Build on AWS
  amazon.aws.ec2_instance:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ ec2_name }}"
    instance_type: "{{ aws_instance }}"
    image_id: "{{ aws_ami_id }}"
    key_name: "{{ aws_key_name }}"
    security_group: "{{ aws_name_security_group }}"
    wait: true